# Generated by Django 4.2.7 on 2023-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='student',
            name='classs',
            field=models.CharField(default='DefaultClass', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateTimeField(default='2021-01-01', verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='Default email', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.CharField(default='DefaultMentor', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='Default phone', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='DefaultSubject', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Default name', max_length=200),
        ),
    ]
