# Generated by Django 4.2.7 on 2023-11-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_remove_student_roll_student_classs_student_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
