# Generated by Django 4.2.7 on 2023-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
