# Generated by Django 4.2.7 on 2023-11-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_student_classs_student_mentor_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
