# Generated by Django 4.2.7 on 2023-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0009_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mentorname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='mentorname',
            new_name='ownername',
        ),
    ]
