# Generated by Django 4.2.7 on 2023-11-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_mentorcred_rename_mentorname_owner_ownername'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField()),
                ('_class', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('mentor', models.CharField(max_length=255)),
                ('renrollment', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classs',
            new_name='_class',
        ),
    ]
