# Generated by Django 4.2.7 on 2023-11-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_renrolldata_rename_classs_student__class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='number',
            new_name='phone',
        ),
    ]
